name: "kubeval"
version: "0.15.0"
usage: "Validate Helm charts"
description: |-
  "Validate Helm charts against the Kubernetes schemas"
command: "$HELM_PLUGIN_DIR/scripts/run.sh"

hooks:
  install: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"

useTunnel: false
ignoreFlags: false
